zookeeper:
  image: eventuateio/eventuate-zookeeper:0.4.0.RELEASE
  ports:
    - 2181:2181

activemq:
  image: eventuateio/eventuate-activemq:0.3.0.RELEASE
  ports:
    - 8161:8161
    - 61616:61616
    - 61613:61613
    - 1883:1883
    - 61614:61614

mssql:
  image: eventuateio/eventuate-mssql:0.4.0.RELEASE
  ports:
    - 1433:1433
  environment:
    SA_PASSWORD: Eventuate123!
    ACCEPT_EULA: Y

cdc-service:
  image: eventuateio/eventuate-cdc-service:0.4.0.RELEASE
  ports:
    - "8099:8080"
  links:
    - mssql
    - activemq
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql:1433;databaseName=eventuate
    SPRING_DATASOURCE_USERNAME: sa
    SPRING_DATASOURCE_PASSWORD: Eventuate123!
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.microsoft.sqlserver.jdbc.SQLServerDriver
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    ACTIVEMQ_URL: tcp://activemq:61616
    ACTIVEMQ_USER: eventuateuser
    ACTIVEMQ_PASSWORD: eventuatepassword
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
    EVENTUATELOCAL_CDC_READER_NAME: ${EVENTUATELOCAL_CDC_READER_NAME}
    EVENTUATELOCAL_CDC_OFFSET_STORE_KEY: ${EVENTUATELOCAL_CDC_OFFSET_STORE_KEY}
    EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID: ${EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID}
    EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC: ${EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC}
    EVENTUATE_DATABASE_SCHEMA: ${EVENTUATE_DATABASE_SCHEMA}
    SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
