zookeeper:
  image: eventuateio/eventuate-zookeeper:0.4.0.RELEASE
  ports:
    - 2181:2181

rabbitmq:
  image: eventuateio/eventuate-rabbitmq:0.3.0.RELEASE
  ports:
    - 5672:5672

postgres:
  image: eventuateio/eventuate-postgres:0.4.0.RELEASE
  ports:
    - 5432:5432
  environment:
    POSTGRES_USER: eventuate
    POSTGRES_PASSWORD: eventuate

cdc-service:
  image: eventuateio/eventuate-cdc-service:0.4.0.RELEASE
  ports:
    - "8099:8080"
  links:
    - postgres
    - rabbitmq
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
    SPRING_DATASOURCE_USERNAME: eventuate
    SPRING_DATASOURCE_PASSWORD: eventuate
    SPRING_DATASOURCE_TEST_ON_BORROW: "true"
    SPRING_DATASOURCE_VALIDATION_QUERY: SELECT 1
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    RABBITMQ_URL: rabbitmq
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
    EVENTUATELOCAL_CDC_READER_NAME: ${EVENTUATELOCAL_CDC_READER_NAME}
    EVENTUATELOCAL_CDC_OFFSET_STORE_KEY: ${EVENTUATELOCAL_CDC_OFFSET_STORE_KEY}
    EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID: ${EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID}
    EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC: ${EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC}
    EVENTUATE_DATABASE_SCHEMA: ${EVENTUATE_DATABASE_SCHEMA}
    SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}